# Generated by Django 5.1.1 on 2024-10-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CateoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=1000, verbose_name='Category Name')),
                ('category', models.ManyToManyField(to='task.taskmodel')),
            ],
        ),
    ]
