# Generated by Django 5.1.1 on 2024-10-01 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cateorymodel',
            name='category',
        ),
    ]
