# Generated by Django 5.1.1 on 2024-10-01 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_taskmodel_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskmodel',
            old_name='task',
            new_name='category',
        ),
    ]
